# -*- coding: utf-8 -*-
"""interactive_streetlights_map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1il2syn9mtousv3bKS3SCzsZFczpGAPmG
"""

!pip install geopandas descartes shapely rtree

"""Interactive Map with Folium
*   Mapping points with Folium
https://georgetsilva.github.io/posts/mapping-points-with-folium/
*   https://automating-gis-processes.github.io/2017/lessons/L5/interactive-map-folium.html
*   https://blog.prototypr.io/interactive-maps-with-python-part-1-aa1563dbe5a9

Static Map Geopands
*   https://towardsdatascience.com/geopandas-101-plot-any-data-with-a-latitude-and-longitude-on-a-map-98e01944b972


Notebook for installing libspationindex 
https://drive.google.com/file/d/1N7i9zmOwVcUzd4eHWZux4p_WTBMZHi8C/view?usp=sharing

Datasets:
Street Light
*   Street Light location Github: 
        
        2019-Team-201/Hackathon Datasets/StreetLight_LocationsClean.csv
      
Traffic      
*   sd_traffic_2015_stations.csv (uploaded by tommy but not on github anymore)

*   sd_traffic_2015.csv (see above)
"""

import geopandas
import descartes
import matplotlib.pyplot as plt
import pandas as pd
from shapely.geometry import Point, Polygon
import folium

#Load csv files
#sd_traffic_stations = pd.read_csv('sd_traffic_2015_stations.csv')
#sd_traffic = pd.read_csv('sd_traffic_2015.csv')
station_lights =  pd.read_csv('traffic_lights_data_2015.csv') 
station_lights.head()

locationlist = station_lights[['lights_lat', 'lights_long']].values.tolist()
print(locationlist)

street_lights =  pd.read_csv('StreetLight_LocationsClean.csv')
street_lights.shape

#Create folium map
map = folium.Map(location=[32.732428,	-117.111704], tiles='Stamen Toner', zoom_start=12, control_scale=True)
marker_cluster = folium.MarkerCluster().add_to(map)

marker = folium.CircleMarker(location=[32.692872,  -117.121745], radius=8000, 
                             fill_color='#3186cc', fill_opacity=0.1)
                    
                           
marker.add_to(map)

marker2 = folium.Marker(location=[32.692872,  -117.121745], popup="Traffic station_id 119030 / long:32.692872  lat:-117.121745 / Streetlights {}".format(station_lights['no. of lights'][0]) )
                             
  
marker2.add_to(map)



for point in range(0, 20000): 
  #print(new_df['traffic_volume_counted_after_1700_to_1800'][point])
  #traffic_count = str(new_df['traffic_volume_counted_after_1700_to_1800'][point])
  folium.Marker(locationlist[point], popup='Traffic lights').add_to(marker_cluster)

map

# Filepath to the output
outfp = "sd_streetlights_map.html"

# Save the map
map.save(outfp)